apiVersion: v1
kind: Service
metadata:
  labels:
    app: hrm-go-graphql
  name: hrm-go-graphql
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hrm-go-graphql
  type: ClusterIP
