apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hrm-go-graphql-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hrm-go-graphql
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80