// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tag struct {
	// The id of the tag (Guid)
	ID string `json:"id"`
	// The name of the tag
	Name string `json:"name"`
}
